apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2021-05-27T04:04:28Z"
  generateName: nginx-deployment-8ffd6f98c-
  labels:
    app: nginx
    pod-template-hash: 8ffd6f98c
  name: nginx-deployment-8ffd6f98c-55rvh
  namespace: matheusmc
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nginx-deployment-8ffd6f98c
    uid: 698de1cb-2ae7-40ea-8635-de168e6d72b9
  resourceVersion: "102596880"
  selfLink: /api/v1/namespaces/matheusmc/pods/nginx-deployment-8ffd6f98c-55rvh
  uid: 9f66e0ab-af89-49e9-b3ff-ce0e39f912e4
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 1m
        memory: 128Mi
      requests:
        cpu: 1m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-z4dps
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-172-22-182-87.ec2.internal
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: observability
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-z4dps
    secret:
      defaultMode: 420
      secretName: default-token-z4dps
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-05-27T04:04:28Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-05-27T04:04:34Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-05-27T04:04:34Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-05-27T04:04:28Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://8c32c6d097c34df4ea096dd7a177be847969d3b632d3b687c295e13cb5d11f14
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:6d75c99af15565a301e48297fa2d121e15d80ad526f8369c526324f0f7ccb750
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-05-27T04:04:33Z"
  hostIP: 172.22.182.87
  phase: Running
  podIP: 172.22.182.86
  podIPs:
  - ip: 172.22.182.86
  qosClass: Guaranteed
  startTime: "2021-05-27T04:04:28Z"
