---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sidecar
  labels:
    app: pod-with-sidecar
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
    # Main application container
    - name: app-container
      # Simple application: write the current date
      # to the log file every five seconds
      image: alpine # alpine is a simple Linux OS image
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/log/app.txt; sleep 5;done"]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log

    # Sidecar container
    - name: sidecar-container
      # Simple sidecar: display log files using nginx.
      # In reality, this sidecar would be a custom image
      # that uploads logs to a third-party or storage service.
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-logs
          mountPath: /usr/share/nginx/html # nginx-specific mount path
---
apiVersion: v1
kind: Service
metadata:
  name: init-demo
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: pod-with-sidecar